# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 30a2cedfec821d859be3324458df00d87aab7c221c44e615b8e8a21d3e1efcb989490de31bee65e9f7a90fdcf78a90a5c63e73aaacc149245bf888662eb5ce06

test:
  secret_key_base: 3b0ac44d655203165d0a791d93153c50869c1076d2a6529a5c605791908a683452b3256e4e8eb82d14dd6b30345c085c14c7c6b098a617c6c0fa1804fe33dc7f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
